import { AUDIO_MODE_PRESETS, PLAYLISTS, RUNNING_PLANS } from "@/data";

export const DEFAULT_PLAN = RUNNING_PLANS[0];
export const DEFAULT_PLAYLIST = PLAYLISTS[0];
export const DEFAULT_AUDIO_MODE = AUDIO_MODE_PRESETS[0];
